### Get all products
GET http://localhost:3000/products
Content-Type: application/json

### Get all reviews
GET http://localhost:3000/reviews
Content-Type: application/json

###

### Get a single product by ID
GET http://localhost:3000/products/6aac4cd44874b75dba48b415
Content-Type: application/json

### Get a single review by ID
GET http://localhost:3000/reviews/6ab1d4734d206d5e0039a6ab
Content-Type: application/json

###

### Create a new product
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Product name",
    "sku": "ABC-DFG-001",
    "price": 0,
    "stock": 0,
    "category": "category",
    "isActive": true,
    "createdAt": "2026-09-17T18:30:00.000Z"
}

### Create a new review
POST http://localhost:3000/reviews
Content-Type: application/json

{
  "productId": "123412341234123412341234",
    "userId": "123412341234123412341234",
    "reviewerName": "Jhon Doe",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    "rating": 5,
    "isVerifiedPurchase": true,
    "createdAt": "2026-09-17T18:30:00.000Z"
}

###

### Update an existing product
PUT http://localhost:3000/products/6aad8bdd740f558a54945c45
Content-Type: application/json

{
    "name": "Product name",
    "sku": "ABC-DFG-001",
    "price": 0,
    "stock": 0,
    "category": "category",
    "isActive": true,
    "createdAt": "2026-09-17T18:30:00.000Z"
}

### Update an existing review
PUT http://localhost:3000/reviews/6aac4ced4874b75dba48b433
Content-Type: application/json

{
  "productId": "0",
    "userId": "0",
    "reviewerName": "Jhon Doe",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    "rating": 5,
    "isVerifiedPurchase": true,
    "createdAt": "2026-09-17T18:30:00.000Z"
}

###

### Delete a product
DELETE http://localhost:3000/products/6aad8bdd740f558a54945c45
Content-Type: application/json

### Delete a review
DELETE http://localhost:3000/reviews/6aac4ced4874b75dba48b433
Content-Type: application/json
